players = {
    "Quarterbacks": {
        "Drew Allar": "Penn State",
        "Luke Altmyer": "Illinois",
        "Carson Beck": "Miami",
        "Jalon Daniels": "Kansas",
        "Joe Fagnano": "UConn",
        "Taylen Green": "Arkansas",
        "Haynes King": "Georgia Tech",
        "Cade Klubnik": "Clemson",
        "Fernando Mendoza": "Indiana",
        "Behren Morton": "Texas Tech",
        "Garrett Nussmeier": "LSU",
        "Diego Pavia": "Vanderbilt",
        "Cole Payton": "North Dakota State",
        "Sawyer Robertson": "Baylor",
        "Ty Simpson": "Alabama",
    },

    "Running Backs": {
        "Kaytron Allen": "Penn State",
        "Max Bredeson": "Michigan",
        "Demond Claiborne": "Wake Forest",
        "Jonah Coleman": "Washington",
        "CJ Donaldson": "Ohio State",
        "Rahsul Faison": "South Carolina",
        "Eli Heidenreich": "Navy",
        "Roman Hemby": "Indiana",
        "Robert Henry Jr.": "UTSA",
        "Emmett Johnson": "Nebraska",
        "Jeremiyah Love": "Notre Dame",
        "Seth McGowan": "Kentucky",
        "Jam Miller": "Alabama",
        "Le'Veon Moss": "Texas A&M",
        "Jadarian Price": "Notre Dame",
        "Adam Randall": "Clemson",
        "Desmond Reid": "Pittsburgh",
        "Nicholas Singleton": "Penn State",
        "J'Mari Taylor": "Virginia",
        "Mike Washington Jr.": "Arkansas",
        "Noah Whittington": "Oregon",
    },

    "Wide Receivers": {
        "Aaron Anderson": "LSU",
        "Vinny Anthony II": "Wisconsin",
        "Chris Bell": "Louisville",
        "Dillon Bell": "Georgia",
        "Skyler Bell": "UConn",
        "Malik Benson": "Oregon",
        "Germie Bernard": "Alabama",
        "Denzel Boston": "Washington",
        "Zachariah Branch": "Georgia",
        "Chris Brazzell II": "Tennessee",
        "Barion Brown": "LSU",
        "Deion Burks": "Oklahoma",
        "Jeff Caldwell": "Cincinnati",
        "Josh Cameron": "Baylor",
        "Kevin Coleman Jr.": "Missouri",
        "KC Concepcion": "Texas A&M",
        "Omar Cooper Jr.": "Indiana",
        "CJ Daniels": "Miami",
        "Caleb Douglas": "Texas Tech",
        "Malachi Fields": "Notre Dame",
        "Emmanuel Henderson Jr.": "Kansas",
        "Chris Hilton Jr.": "LSU",
        "Jordan Hudson": "SMU",
        "Ted Hurst": "Georgia State",
        "Caullin Lacy": "Louisville",
        "Bryce Lance": "North Dakota State",
        "Ja'Kobi Lane": "USC",
        "Kendrick Law": "Kentucky",
        "Makai Lemon": "USC",
        "Eric McAlister": "TCU",
        "Donaven McCulley": "Michigan",
        "Eric Rivers": "Georgia Tech",
        "Chase Roberts": "BYU",
        "Elijah Sarratt": "Indiana",
        "De'Zhaun Stribling": "Mississippi",
        "J. Michael Sturdivant": "Florida",
        "Carnell Tate": "Ohio State",
        "Zavion Thomas": "LSU",
        "Brenen Thompson": "Mississippi State",
        "Jordyn Tyson": "Arizona State",
        "Reggie Virgil": "Texas Tech",
        "Harrison Wallace III": "Mississippi",
        "Jalen Walthall": "Incarnate Word",
        "Kaden Wetjen": "Iowa",
        "Antonio Williams": "Clemson",
        "Colbie Young": "Georgia",
    },

    "Tight Ends": {
        "Dallen Bentley": "Utah",
        "Nate Boerkircher": "Texas A&M",
        "Josh Cuevas": "Alabama",
        "Oscar Delp": "Georgia",
        "Khalil Dinkins": "Penn State",
        "Jack Endries": "Texas",
        "John Michael Gyllenborg": "Wyoming",
        "Matthew Hibner": "SMU",
        "Justin Joly": "N.C. State",
        "Will Kacmarek": "Ohio State",
        "Jaren Kanak": "Oklahoma",
        "Miles Kitselman": "Tennessee",
        "Max Klare": "Ohio State",
        "Marlin Klein": "Michigan",
        "Tanner Koziol": "Houston",
        "RJ Maryland": "SMU",
        "Lake McRee": "USC",
        "Riley Nowakowski": "Indiana",
        "Eli Raridon": "Notre Dame",
        "DJ Rogers": "TCU",
        "Sam Roush": "Stanford",
        "Joe Royer": "Cincinnati",
        "Kenyon Sadiq": "Oregon",
        "Bauer Sharp": "LSU",
        "Eli Stowers": "Vanderbilt",
        "Michael Trigg": "Baylor",
        "Dae'Quan Wright": "Mississippi",
    },

    "Offensive Linemen": {
        "Chris Adams": "Memphis",
        "Austin Barber": "Florida",
        "Evan Beerntsen": "Northwestern",
        "Markel Bell": "Miami",
        "Chase Bisontis": "Texas A&M",
        "Jude Bowry": "Boston College",
        "Parker Brailsford": "Alabama",
        "Joshua Braun": "Kentucky",
        "Travis Burke": "Memphis",
        "Jager Burton": "Kentucky",
        "DJ Campbell": "Texas",
        "Fernando Carmona": "Arkansas",
        "Kage Casey": "Boise State",
        "Pat Coogan": "Indiana",
        "Anez Cooper": "Miami",
        "Dametrious Crownover": "Texas A&M",
        "Enrique Cruz Jr.": "Kansas",
        "J.C. Davis": "Illinois",
        "Garrett DiGiorgio": "UCLA",
        "Gennings Dunker": "Iowa",
        "Fa'alili Fa'amoe": "Wake Forest",
        "Spencer Fano": "Utah",
        "Jalen Farmer": "Kentucky",
        "Monroe Freeling": "Georgia",
        "Matt Gulbin": "Michigan State",
        "Alex Harkey": "Oregon",
        "Sam Hecht": "Kansas State",
        "Alan Herron": "Maryland",
        "Max Iheanachor": "Arizona State",
        "Olaivavega Ioane": "Penn State",
        "Logan Jones": "Iowa",
        "Connor Lew": "Auburn",
        "Caleb Lomu": "Utah",
        "Francis Mauigoa": "Miami",
        "Blake Miller": "Clemson",
        "Micah Morris": "Georgia",
        "Febechi Nwaiwu": "Oklahoma",
        "Brian Parker II": "Duke",
        "Diego Pounds": "Mississippi",
        "Emmanuel Pregnon": "Oregon",
        "Kadyn Proctor": "Alabama",
        "Ar'maj Reed-Adams": "Texas A&M",
        "Jaeden Roberts": "Alabama",
        "Keylan Rutledge": "Georgia Tech",
        "Billy Schrauth": "Notre Dame",
        "Drew Shelton": "Penn State",
        "Jake Slaughter": "Florida",
        "Beau Stephens": "Iowa",
        "Logan Taylor": "Boston College",
        "Caleb Tiernan": "Northwestern",
        "Keagen Trost": "Missouri",
        "Dillon Wade": "Auburn",
        "Aamil Wagner": "Notre Dame",
        "Carver Willis": "Washington",
        "Isaiah World": "Oregon",
        "Jeremiah Wright": "Auburn",
        "Trey Zuhn III": "Texas A&M",
    },

    "Defensive Linemen": {
        "Vincent Anthony Jr.": "Duke",
        "David Bailey": "Texas Tech",
        "Rueben Bain Jr.": "Miami",
        "Cameron Ball": "Arkansas",
        "Caleb Banks": "Florida",
        "Jaishawn Barham": "Michigan",
        "Nick Barrett": "South Carolina",
        "Rayshaun Benny": "Michigan",
        "DeMonte Capehart": "Clemson",
        "Brandon Cleveland": "N.C. State",
        "Dontay Corleone": "Cincinnati",
        "Keyron Crawford": "Auburn",
        "Caden Curry": "Ohio State",
        "Dani Dennis-Sutton": "Penn State",
        "Zane Durant": "Penn State",
        "Bryson Eason": "Tennessee",
        "Deven Eastern": "Minnesota",
        "Logan Fano": "Utah",
        "Keldric Faulk": "Auburn",
        "Skyler Gill-Howard": "Texas Tech",
        "George Gumbs Jr.": "Florida",
        "David Gusta": "Kentucky",
        "Gracen Halton": "Oklahoma",
        "Zxavian Harris": "Mississippi",
        "Romello Height": "Texas Tech",
        "Cashius Howell": "Texas A&M",
        "Aidan Hubbard": "Northwestern",
        "Lee Hunter": "Texas Tech",
        "Quintayvious Hutchins": "Boston College",
        "Gabe Jacas": "Illinois",
        "Darrell Jackson Jr.": "Florida State",
        "Bobby Jamison-Travis": "Auburn",
        "Marvin Jones Jr.": "Oklahoma",
        "Joshua Josephs": "Tennessee",
        "Tim Keenan III": "Alabama",
        "Nyjalik Kelly": "UCF",
        "Malachi Lawrence": "UCF",
        "Max Llewellyn": "Iowa",
        "Anthony Lucas": "USC",
        "Jackie Marshall": "Baylor",
        "Chris McClellan": "Missouri",
        "Kayden McDonald": "Ohio State",
        "Akheem Mesidor": "Miami",
        "Christen Miller": "Georgia",
        "Derrick Moore": "Michigan",
        "Trey Moore": "Texas",
        "Tyler Onyedim": "Texas A&M",
        "Domonique Orange": "Iowa State",
        "LT Overton": "Alabama",
        "T.J. Parker": "Clemson",
        "Patrick Payton": "LSU",
        "Kaleb Proctor": "Southeastern Louisiana",
        "Jack Pyburn": "LSU",
        "Albert Regis": "Texas A&M",
        "Mason Reiger": "Wisconsin",
        "Tyreak Sapp": "Florida",
        "Gary Smith III": "UCLA",
        "R Mason Thomas": "Oklahoma",
        "Nadame Tucker": "Western Michigan",
        "Damonic Williams": "Oklahoma",
        "Wesley Williams": "Duke",
        "Peter Woods": "Clemson",
        "Zion Young": "Missouri",
    },

    "Linebackers": {
        "CJ Allen": "Georgia",
        "Lander Barton": "Utah",
        "Wesley Bissainthe": "Miami",
        "Bryce Boettcher": "Oregon",
        "Kendal Daniels": "Oklahoma",
        "Kaleb Elarms-Orr": "TCU",
        "Keyshaun Elliott": "Arizona State",
        "Aiden Fisher": "Indiana",
        "Eric Gentry": "USC",
        "Jake Golday": "Cincinnati",
        "Owen Heinecke": "Oklahoma",
        "Anthony Hill Jr.": "Texas",
        "Justin Jefferson": "Alabama",
        "Jack Kelly": "BYU",
        "Deontae Lawson": "Alabama",
        "Kyle Louis": "Pittsburgh",
        "Red Murdock": "Buffalo",
        "Namdi Obiazor": "TCU",
        "Harold Perkins Jr.": "LSU",
        "Arvell Reese": "Ohio State",
        "Jacob Rodriguez": "Texas Tech",
        "Jimmy Rolder": "Michigan",
        "Karson Sharar": "Iowa",
        "Xavian Sorey Jr.": "Arkansas",
        "Sonny Styles": "Ohio State",
        "Josiah Trotter": "Missouri",
        "Scooby Williams": "Texas A&M",
        "Wade Woodaz": "Clemson",
        "Taurean York": "Texas A&M",
    },

    "Defensive Backs": {
        "Keith Abney II": "Arizona State",
        "Marcus Allen": "North Carolina",
        "Jadon Canady": "Oregon",
        "Brandon Cisse": "South Carolina",
        "Bud Clark": "TCU",
        "Tacario Davis": "Washington",
        "Mansoor Delane": "LSU",
        "Charles Demmings": "Stephen F. Austin",
        "Thaddeus Dixon": "North Carolina",
        "Caleb Downs": "Ohio State",
        "Daylen Everette": "Georgia",
        "Bishop Fitzgerald": "USC",
        "Andre Fuller": "Toledo",
        "Jaylon Guilbeau": "Texas",
        "TJ Hall": "Iowa",
        "Ahmari Harvey": "Georgia Tech",
        "A.J. Haulcy": "LSU",
        "Colton Hood": "Tennessee",
        "Jalen Huskey": "Maryland",
        "Davison Igbinosun": "Ohio State",
        "Domani Jackson": "Alabama",
        "Chris Johnson": "San Diego State",
        "Dalton Johnson": "Arizona",
        "Jalon Kilgore": "South Carolina",
        "Will Lee III": "Texas A&M",
        "Hezekiah Masses": "Cal",
        "Jermod McCoy": "Tennessee",
        "Latrell McCutchin Sr.": "Houston",
        "Emmanuel McNeil-Warren": "Toledo",
        "Devin Moore": "Florida",
        "Louis Moore": "Indiana",
        "Ahmaad Moses": "SMU",
        "Malik Muhammad": "Texas",
        "Julian Neal": "Arkansas",
        "Xavier Nwankpa": "Iowa",
        "VJ Payne": "Kansas State",
        "D'Angelo Ponds": "Indiana",
        "Toriano Pride Jr.": "Missouri",
        "Ephesians Prysock": "Washington",
        "Kamari Ramsey": "USC",
        "Chandler Rivers": "Duke",
        "Keionte Scott": "Miami",
        "DeShon Singleton": "Nebraska",
        "Avery Smith": "Toledo",
        "Genesis Smith": "Arizona",
        "Robert Spears-Jennings": "Oklahoma",
        "Treydan Stukes": "Arizona",
        "Lorenzo Styles Jr.": "Ohio State",
        "Michael Taaffe": "Texas",
        "Avieon Terrell": "Clemson",
        "Dillon Thieneman": "Oregon",
        "Jakobe Thomas": "Miami",
        "Zakee Wheatley": "Penn State",
        "Collin Wright": "Stanford",
    },

    "Specialists": {
        "Tommy Doman Jr.": "Florida",
        "Ryan Eckley": "Michigan State",
        "Trey Smack": "Florida",
        "Drew Stevens": "Iowa",
        "Jack Stonehouse": "Syracuse",
        "Brett Thorson": "Georgia",
        "Dominic Zvada": "Michigan",
    }
}
