"""add preseason points to players

Revision ID: 20027af51d14
Revises: 68c7b68b3180
Create Date: 2026-07-17 10:19:43.844550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20027af51d14'
down_revision = '68c7b68b3180'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preseason_points', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('preseason_points')

    # ### end Alembic commands ###
