"""sync schema

Revision ID: 2524deb04fef
Revises: 90d054dce8e2
Create Date: 2026-04-20 16:38:59.510396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2524deb04fef'
down_revision = '90d054dce8e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prediction', schema=None) as batch_op:
        batch_op.alter_column('player_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('player_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('draft_position_group',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.create_foreign_key("fk_prediction_player_id", 'player', ['player_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prediction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('draft_position_group',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('player_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('player_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
