"""make sleeper id required

Revision ID: 3e8e898cd599
Revises: 4aa18cfe5b3d
Create Date: 2026-07-19 21:45:46.497122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e8e898cd599'
down_revision = '4aa18cfe5b3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.alter_column('sleeper_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('route_usage', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route_usage', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.alter_column('sleeper_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
