"""add game api fields

Revision ID: 48cff0484edd
Revises: c9c49caf9f66
Create Date: 2026-08-19 13:26:07.375218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48cff0484edd'
down_revision = 'c9c49caf9f66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('postseason', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('status_state', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('venue', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('home_q1', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('home_q2', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('home_q3', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('home_q4', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('home_ot', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('away_q1', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('away_q2', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('away_q3', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('away_q4', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('away_ot', sa.Integer(), nullable=True))
        batch_op.alter_column('season',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('week',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('home_team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('away_team_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.alter_column('away_team_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('home_team_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('week',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('season',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('away_ot')
        batch_op.drop_column('away_q4')
        batch_op.drop_column('away_q3')
        batch_op.drop_column('away_q2')
        batch_op.drop_column('away_q1')
        batch_op.drop_column('home_ot')
        batch_op.drop_column('home_q4')
        batch_op.drop_column('home_q3')
        batch_op.drop_column('home_q2')
        batch_op.drop_column('home_q1')
        batch_op.drop_column('venue')
        batch_op.drop_column('summary')
        batch_op.drop_column('status_state')
        batch_op.drop_column('postseason')

    # ### end Alembic commands ###
