"""add preseason position

Revision ID: 68c7b68b3180
Revises: a013c4b665ed
Create Date: 2026-07-16 13:46:35.279537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68c7b68b3180'
down_revision = 'a013c4b665ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prediction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preseason_position', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prediction', schema=None) as batch_op:
        batch_op.drop_column('preseason_position')

    # ### end Alembic commands ###
