"""make sleeper id unique

Revision ID: a013c4b665ed
Revises: dc6059715d2b
Create Date: 2026-07-13 16:18:39.444088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a013c4b665ed'
down_revision = 'dc6059715d2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.alter_column('sleeper_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.create_unique_constraint("uq_player_sleeper_id", ["sleeper_id"])

    with op.batch_alter_table('route_usage', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route_usage', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_constraint("uq_player_sleeper_id", type_="unique")
        batch_op.alter_column('sleeper_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
